### ISSUE TITLE
NCBI nucleotide download issue

### ISSUE THREAD

**Issue by saraswaminathan** [gjeunen/reference_database_creator#68]
Hi there - I am using the very new version of the crabs package and have successfully gotten it running, have downloaded the NCBI taxonomy, and have downloaded sequences from BOLD. Now I am trying to download sequences from NCBI nucleotide. When I run the following query: 

`crabs --download-ncbi --query '"16S"[All Fields]' --species Acanthophora --output /Users/saraswaminathan/Desktop/crabs/crabs_testing/ncbi_nucleotide1.fasta --email saraswami94@gmail.com --database nucleotide --batchsize 5000`

I get the following error: 
```
Traceback (most recent call last):
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 844, in <module>
    crabs()
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 542, in crabs
    console.print(f"[cyan]|             Results[/] | Number of sequences downloaded: {total_downloaded_seqs}/{total_read_count} ({round(total_downloaded_seqs / total_read_count * 100, 2)}%)")
                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

I also tried the same command, but with a species list .txt file instead of the single taxa:

`crabs --download-ncbi --query '"16S"[All Fields]' --species Acanthophora --output /Users/saraswaminathan/Desktop/crabs/crabs_testing/ncbi_nucleotide1.fasta --email saraswami94@gmail.com --database nucleotide --batchsize 5000
`

When I do that, I get this error: 

```
File "/Users/saraswaminathan/reference_database_creator/crabs", line 844, in <module>
    crabs()
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 538, in crabs
    total_read_count, ncbi_info_dict = ncbi_download_info(console, columns, query_list, database_, email_)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/function/crabs_functions.py", line 289, in ncbi_download_info
    query_key, web_env, matching_seq_count = retrieve_init_ncbi_info(database_, email_, item)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/function/crabs_functions.py", line 248, in retrieve_init_ncbi_info
    query_key = content_str.split('<QueryKey>')[1].split('</QueryKey>')[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Thanks very much!!!!

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

Thank you for bringing this bug to our attention. There was an issue with the NCBI query building code when a species was provided. I've updated the code (`crabs --version 1.0.1`) and all should work now. 

Best wishes,
Gert-Jan

**Comment by saraswaminathan** [comment]
Thank you! With the updated package, I am still getting errors when I try to input a .txt file as the species list for the ncbi download. However, I am just using a for-loop the way I did for the BOLD download, which is working. I get the ZeroDivisionError for any taxa where the search in ncbi returns 0 hits, but in this case it just skips over this taxon and does not create a .fasta file for it, which is fine.

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

Apologies, I overlooked the issue with the species text file.

The new version (crabs --version 1.0.2) now fixes the ZeroDivisionError reported by CRABS when 0 sequences are downloaded. 

I can't seem to recreate the error you receive when reading from a species text file. Do you mind attaching the text file to your response, as well as the code you used? This might help in trying to figure out the issue.

Best wishes,
Gert-Jan

**Comment by saraswaminathan** [comment]
Hi Gert-Jan, 
I updated to 1.0.2 and ran the following code: 

`crabs --download-ncbi --query '"16S"[All Fields]' --species /Users/saraswaminathan/Desktop/crabs_old/atlantic_genera_algae1.txt --output /Users/saraswaminathan/Desktop/crabs/ncbi_txt_test.fasta --email saraswami94@gmail.com --database nucleotide --batchsize 5000`

I'm attaching the text file I used. It appeared to be running ok but then quit at ~20% with the following error message: 

```
Traceback (most recent call last):
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 847, in <module>
    crabs()
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/crabs", line 538, in crabs
    total_read_count, ncbi_info_dict = ncbi_download_info(console, columns, query_list, database_, email_)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/function/crabs_functions.py", line 289, in ncbi_download_info
    query_key, web_env, matching_seq_count = retrieve_init_ncbi_info(database_, email_, item)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saraswaminathan/reference_database_creator/function/crabs_functions.py", line 248, in retrieve_init_ncbi_info
    query_key = content_str.split('<QueryKey>')[1].split('</QueryKey>')[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
[atlantic_genera_algae1.txt](https://github.com/user-attachments/files/17365750/atlantic_genera_algae1.txt)

Thank you!! 
Sara

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

Thank you very much for the example and the text file. This is extremely helpful! I ran the code below, which mirrors your input and managed to download the NCBI data without issue. Please see code and output below.

```{code-block} bash
crabs --download-ncbi --query '"16S"[All Fields]' --species atlantic_genera_algae1.txt --output ncbi_txt_test.fasta --email gjeunen@gmail.com --database nucleotide
```

```{admonition}
/// CRABS | v1.0.2

|            Function | Download NCBI database
|         "--species" | identified as document with 100 name(s)
|Retrieving NCBI info | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:01:43
|         Downloading | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 100% 0:00:04 0:16:44
|             Results | Number of sequences downloaded: 50386/50507 (99.76%)
```

What I think is happening is that there might be some connection issues with the NCBI servers. This could either be due to an overload of traffic on the NCBI servers when you're running your code or that the NCBI servers have limited your access. This might sometimes happen when you're taking up too much traffic by downloading huge chunks of data.

The reason why I think this is the issue, is that the error indicates that the initial data retrieved from NCBI by CRABS, which CRABS parses and uses to download the actual sequences, doesn't seem to exist. 

In `CRABS --version 1.0.3`, I have now added a check to ensure a connection to the NCBI servers can be made. CRABS will try this 3 times. If the connection cannot be made in three consecutive tries, CRABS will report an error and quit the download from the NCBI servers.

Please let me know if this solves your issue.

Best wishes,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @saraswaminathan,

I will assume this issue has been fixed and will close this item, but please let me know if issues persist.

Thanks,
Gert-Jan
